[package]
name = "icedragon"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
chrono = "0.4"
clap = { version = "4.5", features = ["derive"] }
env_logger = "0.11"
log = "0.4"
target-lexicon = "0.12"
thiserror = { version = "1.0.64" }
uuid = { version = "1.10", features = ["v4"] }
which = "6.0"

[[bin]]
name = "icedragon"
