name: Release

on:
  release:
    types: [published]

jobs:
  upload-bins:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-musl
          - x86_64-unknown-linux-musl
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: icedragon
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
